# Generated by Django 5.2.4 on 2025-09-23 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('date_of_delivery', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflows', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflows', to='inventory.item')),
            ],
            options={
                'ordering': ['-date_of_delivery'],
            },
        ),
        migrations.CreateModel(
            name='ProductSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('dispatched', 'Dispatched'), ('returned', 'Returned')], default='in_stock', max_length=20)),
                ('inflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='product_documentation.productinflow')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('sales_order', models.CharField(blank=True, max_length=50)),
                ('dispatch_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='product_documentation.productinflow')),
                ('responsible_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows', to=settings.AUTH_USER_MODEL)),
                ('serial_numbers', models.ManyToManyField(related_name='outflows', to='product_documentation.productserialnumber')),
            ],
            options={
                'ordering': ['-dispatch_date'],
            },
        ),
        migrations.AddIndex(
            model_name='productinflow',
            index=models.Index(fields=['batch'], name='product_doc_batch_e4aff7_idx'),
        ),
    ]
