# Generated by Django 5.2.4 on 2025-09-23 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DwellTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField()),
                ('is_aging', models.BooleanField(default=False)),
                ('storage_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EOQReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=50)),
                ('demand_rate', models.PositiveIntegerField(help_text='Units/year')),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holding_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eoq', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EOQReportV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_rate', models.PositiveIntegerField(help_text='Annual demand in units')),
                ('order_cost', models.DecimalField(decimal_places=2, help_text='Cost per order', max_digits=10)),
                ('holding_cost', models.DecimalField(decimal_places=2, help_text='Holding cost per unit per year', max_digits=10)),
                ('lead_time_days', models.PositiveIntegerField(help_text='Lead time in days')),
                ('safety_stock', models.PositiveIntegerField(default=0, help_text='Safety stock in units')),
                ('eoq', models.PositiveIntegerField(blank=True, help_text='Calculated Economic Order Quantity')),
                ('reorder_point', models.PositiveIntegerField(blank=True, help_text='Inventory level to trigger reorder')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total inventory cost at EOQ', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(help_text='Inventory item', on_delete=django.db.models.deletion.CASCADE, related_name='eoq_reports_v2', to='inventory.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eoq_reports_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EOQ Report V2',
                'verbose_name_plural': 'EOQ Reports V2',
            },
        ),
        migrations.CreateModel(
            name='StockAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('turnover_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obsolescence_risk', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
