# Generated by Django 5.2.4 on 2025-09-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockanalytics',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockanalytics',
            name='obsolescence_risk',
            field=models.CharField(max_length=20),
        ),
    ]
