# Generated by Django 5.2.4 on 2025-10-14 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_stockanalytics_category_and_more'),
        ('inventory', '0009_warehousereceipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Default lead time in days')),
                ('min_order_quantity', models.PositiveIntegerField(blank=True, help_text='Minimum order quantity', null=True)),
                ('discount_threshold', models.PositiveIntegerField(blank=True, help_text='Quantity for discount', null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='eoqreportv2',
            name='holding_cost_breakdown',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Holding cost component', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='eoqreportv2',
            name='inventory_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Inventory turnover ratio', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eoqreportv2',
            name='ordering_cost_breakdown',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ordering cost component', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ReorderQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_quantity', models.PositiveIntegerField(help_text='Quantity to reorder based on EOQ')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ordered', 'Ordered'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_queues', to='inventory.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reorder Queue',
                'verbose_name_plural': 'Reorder Queues',
            },
        ),
        migrations.AddField(
            model_name='eoqreportv2',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.supplier'),
        ),
    ]
