# Generated by Django 5.2.4 on 2025-10-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_supplier_eoqreportv2_holding_cost_breakdown_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dwelltime',
            options={'verbose_name': 'Dwell Time', 'verbose_name_plural': 'Dwell Times'},
        ),
        migrations.AlterModelOptions(
            name='eoqreport',
            options={'verbose_name': 'EOQ Report', 'verbose_name_plural': 'EOQ Reports'},
        ),
        migrations.AlterModelOptions(
            name='stockanalytics',
            options={'verbose_name': 'Stock Analytics', 'verbose_name_plural': 'Stock Analytics'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.RenameField(
            model_name='eoqreportv2',
            old_name='order_cost',
            new_name='ordering_cost',
        ),
    ]
