# Generated by Django 5.2.4 on 2025-10-30 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_dwelltime_options_alter_eoqreport_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoqreportv2',
            name='eoq',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated Economic Order Quantity', null=True),
        ),
        migrations.AlterField(
            model_name='eoqreportv2',
            name='reorder_point',
            field=models.PositiveIntegerField(blank=True, help_text='Inventory level to trigger reorder', null=True),
        ),
        migrations.AlterField(
            model_name='eoqreportv2',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total inventory cost at EOQ', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('inventory', 'Inventory'), ('procurement', 'Procurement'), ('rentals', 'Rentals'), ('combined', 'Combined Dashboard')], max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
