# Generated by Django 5.2.4 on 2025-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_eoqreportv2_eoq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoqreportv2',
            name='item',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reorderqueue',
            name='item',
            field=models.CharField(max_length=255),
        ),
    ]
