# Generated by Django 5.2.4 on 2025-11-02 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_eoqreportv2_item_alter_reorderqueue_item'),
        ('inventory', '0012_warehousereceipt_old_material_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoqreportv2',
            name='item',
            field=models.ForeignKey(help_text='Inventory item', on_delete=django.db.models.deletion.CASCADE, related_name='eoq_reports_v2', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='reorderqueue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_queues', to='inventory.item'),
        ),
        migrations.DeleteModel(
            name='AnalyticsReport',
        ),
    ]
