# Generated by Django 5.2.4 on 2025-09-29 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryactivitylog'),
        ('procurement', '0004_alter_procurementauditlog_action'),
        ('receipts', '0002_receipt_created_at_receipt_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signingreceipt',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stockreceipt',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stockreceipt',
            name='location',
        ),
        migrations.AddField(
            model_name='signingreceipt',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signingreceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_receipts', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='signingreceipt',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='item_name_legacy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='location_legacy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_receipts', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='storage_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipts', to='inventory.storagebin'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signingreceipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signing_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signingreceipt',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_signing_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signingreceipt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipts', to='inventory.item'),
        ),
        migrations.CreateModel(
            name='ReceiptApprovalBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_sign_receipts', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_receipt_approvers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_signing_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Signer',
                'verbose_name_plural': 'Receipt Signers',
                'unique_together': {('user',)},
            },
        ),
    ]
