# Generated by Django 5.2.4 on 2025-09-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_approved_by_rental_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.branch'),
        ),
    ]
