# Generated by Django 5.2.4 on 2025-10-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_equipment_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='status',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
