# Generated by Django 5.2.4 on 2025-10-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_rental_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='rental',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
