# Generated by Django 5.2.4 on 2025-10-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rental_currency_rental_notes_rental_rental_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
