# Generated by Django 5.2.4 on 2025-10-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_rental_due_date_alter_rental_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
