# Generated by Django 5.2.4 on 2025-10-14 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_alter_rental_due_date_alter_rental_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='rentals.branch'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.branch'),
        ),
    ]
