# Generated by Django 5.2.4 on 2025-10-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OVERDUE', 'Overdue Rental'), ('ALMOST_OVERDUE', 'Almost Overdue Rental')], max_length=50),
        ),
    ]
