# Generated by Django 5.2.4 on 2025-10-22 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_by',
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OVERDUE', 'Overdue Rental'), ('ALMOST_OVERDUE', 'Almost Overdue Rental'), ('UNPAID', 'Unpaid Rental')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='code',
            field=models.CharField(default='faf04791', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='amount_in_words',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Paid', max_length=20),
        ),
    ]
