# Generated by Django 5.2.4 on 2025-10-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_remove_reservation_reserved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='code',
            field=models.CharField(default='f0e4207d', max_length=20, unique=True),
        ),
    ]
