# Generated by Django 5.2.4 on 2025-10-22 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_alter_rental_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_for',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OVERDUE', 'Overdue Rental'), ('ALMOST_OVERDUE', 'Almost Overdue Rental')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
