# Generated by Django 5.2.4 on 2025-09-29 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_documentation_new', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinflow',
            options={},
        ),
        migrations.AddField(
            model_name='productinflow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_product_inflows_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productinflow',
            name='batch',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='product_inflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='product_documentation_new.productinflow'),
        ),
    ]
