# Generated by Django 5.2.4 on 2025-09-29 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryactivitylog'),
        ('product_documentation_new', '0002_alter_productinflow_options_productinflow_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinflow',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='productinflow',
            name='batch',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productinflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productinflow',
            name='date_of_delivery',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productinflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productinflow',
            name='vendor',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productoutflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productoutflow',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productoutflow',
            name='dispatch_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productoutflow',
            name='sales_order',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productoutflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('shipped', 'Shipped')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='productinflow',
            index=models.Index(fields=['-created_at'], name='product_doc_created_5b8bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='productinflow',
            index=models.Index(fields=['vendor', 'date_of_delivery'], name='product_doc_vendor_bad4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['status'], name='product_doc_status_38ce46_idx'),
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['product_inflow', 'status'], name='product_doc_product_52c26b_idx'),
        ),
    ]
