# Generated by Django 5.2.4 on 2025-09-29 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_documentation_new', '0003_alter_productinflow_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productoutflow',
            name='responsible_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_product_outflows_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productoutflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productoutflow',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productoutflow',
            name='dispatch_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productoutflow',
            name='sales_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productoutflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
