# Generated by Django 5.2.4 on 2025-09-16 00:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_announcement_companybranding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companybranding',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='companybranding',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='companybranding',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='companybranding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companybranding',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brandings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companybranding',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Company name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companybranding',
            name='secondary_color',
            field=models.CharField(default=django.utils.timezone.now, help_text='Hex code', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companybranding',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companybranding',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding_logos/'),
        ),
        migrations.AlterField(
            model_name='companybranding',
            name='primary_color',
            field=models.CharField(help_text='Hex code, e.g. #1D4ED8', max_length=50),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
