# Generated by Django 5.2.4 on 2025-09-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_companybranding_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybranding',
            name='primary_color',
            field=models.CharField(help_text='Hex code, e.g. #1D4ED8', max_length=50),
        ),
        migrations.AlterField(
            model_name='companybranding',
            name='secondary_color',
            field=models.CharField(help_text='Hex code', max_length=50),
        ),
    ]
