# Generated by Django 5.2.4 on 2025-09-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_storagebin_created_at_storagebin_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryalert',
            name='alert_type',
            field=models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=50),
        ),
        migrations.AlterField(
            model_name='storagebin',
            name='rack',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='storagebin',
            name='row',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='storagebin',
            name='shelf',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
