# Generated by Django 5.2.4 on 2025-10-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='material_id',
            field=models.CharField(editable=False, max_length=6, null=True, unique=True),
        ),
    ]
