# Generated by Django 5.2.4 on 2025-10-14 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_warehouse_city_warehouse_country_warehouse_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('recipient', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_to', models.CharField(blank=True, max_length=255)),
                ('transfer_order_no', models.CharField(blank=True, max_length=100)),
                ('plant_site', models.CharField(blank=True, max_length=100)),
                ('bin_location', models.CharField(blank=True, max_length=100)),
                ('qty_picked', models.PositiveIntegerField(default=0)),
                ('qty_remaining', models.PositiveIntegerField(default=0)),
                ('unloading_point', models.CharField(blank=True, max_length=255)),
                ('original_document', models.CharField(blank=True, max_length=100)),
                ('picker', models.CharField(blank=True, max_length=255)),
                ('controller', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='unique_warehouse_state',
        ),
        migrations.AddField(
            model_name='warehousereceipt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousereceipt',
            name='issued_from_bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storagebin'),
        ),
        migrations.AddField(
            model_name='warehousereceipt',
            name='issued_from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehousereceipt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='warehousereceipt',
            name='stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stockmovement'),
        ),
    ]
