# Generated by Django 5.2.4 on 2025-10-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockmovement_warehouse_receipt'),
    ]

    operations = [
    ]
