# Generated by Django 5.2.4 on 2025-10-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20251016_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousereceipt',
            name='old_material_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
