# Generated by Django 5.2.4 on 2025-11-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_warehousereceipt_old_material_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase Order number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_uid',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
    ]
