# Generated by Django 5.2.4 on 2025-11-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_item_po_number_warehouse_warehouse_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryactivitylog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
