# Generated by Django 5.2.4 on 2025-11-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_inventoryactivitylog_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='material_class',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
