# Generated by Django 5.2.4 on 2026-02-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_item_material_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
