# Generated by Django 5.2.4 on 2026-02-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_item_dollar_cost_item_manufacturing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='material_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
