# Generated by Django 5.2.4 on 2026-02-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_item_material_class_alter_item_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='initial_quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
