# Generated by Django 5.2.4 on 2026-02-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_item_initial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
