# Generated by Django 5.2.4 on 2025-09-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_purchaseorder_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('receive', 'Receive'), ('submit', 'Submit'), ('cancel', 'Cancel')], max_length=20),
        ),
    ]
