# Generated by Django 5.2.4 on 2025-10-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_poitem_discount_percent_poitem_vat_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(blank=True, help_text='Manual order number (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
