# Generated by Django 5.2.4 on 2025-10-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_purchaseorder_order_number_alter_purchaseorder_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='layout',
            field=models.CharField(blank=True, default='default', help_text="Template layout for printing (e.g., 'classic', 'detailed')", max_length=50, null=True),
        ),
    ]
