# Generated by Django 5.2.4 on 2025-10-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_purchaseorder_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)')], default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='requisition',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)')], default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
