# Generated by Django 5.2.4 on 2025-11-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_purchaseorder_currency_requisition_currency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvalboard',
            unique_together=set(),
        ),
    ]
