name: Build and deploy Python app to Azure Web App - newpythonkenyon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Run tests here

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A99DDCD1E1C143609A598656AFE2CE59 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EF7F54976019464FA2EE7A62C22C2343 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F87C05E3EAB34BA4AF723CE0F925B778 }}

      - name: Wait before deploy (avoid SCM restart conflict)
        run: sleep 30

      - name: Deploy to Azure Web App (with retry)
        run: |
          n=0
          until [ "$n" -ge 3 ]
          do
            echo "Attempt $((n+1)) to deploy..."
            if npx @azure/webapps-deploy \
              --app-name newpythonkenyon \
              --slot-name Production; then
              echo "Deployment succeeded!"
              exit 0
            fi
            n=$((n+1))
            echo "Deployment failed. Retrying in 20 seconds..."
            sleep 20
          done
          echo "Deployment failed after 3 attempts."
          exit 1
