# Generated by Django 5.2.4 on 2025-09-23 21:55

import django.db.models.deletion
import warehouse_new.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[warehouse_new.models.validate_quantity])),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('dispatched', 'Dispatched')], default='in_stock', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_new_items', to='inventory.item')),
                ('storage_bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_new_items', to='inventory.storagebin')),
            ],
            options={
                'ordering': ['-last_updated'],
                'constraints': [models.UniqueConstraint(fields=('item', 'storage_bin'), name='unique_warehouse_new_item_bin')],
            },
        ),
    ]
